### ISSUE TITLE
DWN cannot start in docker in MacOS with M1 chip using an ARM image

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-js#1]
Follow the steps found in [README](https://github.com/TBD54566975/dwn-js/blob/main/README.md) to repro. The current workaround is to build a AMD64 image instead but this is strange because M1 is an ARM based chip so it should work.

One theory is that the base nodejs image used in the `dockerfile` is not ARM compatible, but have not investigated further.

**Comment by scrummitch** [comment]
Could be related https://github.com/nodejs/docker-node/issues/1772 

They mention a new build is up now with M1 support
