### ISSUE TITLE
Create examples and simplified custom setup of DWN instances

### ISSUE THREAD

**Issue by sondreb** [TBD54566975/dwn-js#3]
I'm doing some work with the DWN and I see that it might be a good idea to make some examples on customizing the DWN instance in this repo, is that something that would be welcomed as a PR?

The Dwn object allows custom DID resolvers, for example. This repo should have a separate typescript file that demonstrates how to do various overrides of the default features that exists in Dwn (dwn-sdk-js).

**Comment by sondreb** [comment]
In essence, something like this: 

![image](https://user-images.githubusercontent.com/309938/196780338-187bdae8-781a-412e-995e-66d0adbd7f1c.png)

**Comment by thehenrytsai** [comment]
Sorry for the late response! DWN SDK usage examples is a great idea, I am not sure if they should live in `dwn-js` or `dwn-sdk-js`, but PRs for this is welcome in either repo!

**Comment by thehenrytsai** [comment]
Closing, please feel free to open specific issues/PR on what examples you'd like to see!
